### ISSUE TITLE
Feature request: undo/redo

### ISSUE THREAD

**Issue by max-baz** [Gskartwii/teehee#5]
Impressive project! I really like it!

One feature that I think would be really useful for such editor is to support undo and redo operations. 

I know kakoune has a [fancy tree history](https://github.com/mawww/kakoune/wiki/Undo-tree), but maybe a simple linear history would already be good enough of a start.

**Comment by Gskartwii** [comment]
Hey! Thanks for your kind words, I really appreciate it.

Undo and redo are a very good and essential idea. I have already started working on them, though I've got a brick wall because I'm confused by the API of the underlying to byte string rope.

https://github.com/Gskartwii/teehee/blob/deafef86c74a25d6d6a5e81f5af437393c7aa824/src/history.rs#L38-L76

The above function is meant to be able to chain together two deltas (for example two byte insertions in Insert mode) into a single delta, so that an Insert mode change can be stored in a memory efficient manner. I'm just not quite able to work out how to construct the delta, though I will be making an effort to work on this between everything else. Feel free to advise me if you have an idea on that!
